## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
# vacation_df = pd.read_csv("Vacation_Search/WeatherPy_vacation.csv")
# vacation_df.head()
vacation_df = pd.read_csv("../Vacation_Search/WeatherPy_vacation.csv")
vacation_df.head(20)

,City_ID,City,Country,Max Temp,Lat,Lng,Hotel Name
0,2,Luderitz,NaN,70.07,-26.6481,15.1594,LÜDERITZ NEST HOTEL
1,4,Kapaa,US,73.99,22.0752,-159.3190,Sheraton Kauai Resort at Coconut Beach
2,5,Vaini,TO,82.40,-21.2000,-175.2000,Keleti Beach Resort
3,6,Padang,ID,89.60,-0.9492,100.3543,Mercure Padang
4,8,Hobart,AU,87.01,-42.8794,147.3294,St Ives Hobart Accommodation Tasmania
5,11,Richards Bay,ZA,80.51,-28.7830,32.0377,BON Hotel Waterfront Richards Bay
6,16,Rikitea,PF,79.47,-23.1203,-134.9692,Pension Maro'i
7,18,Port-Gentil,GA,80.49,-0.7193,8.7815,Fengshui Residence
8,22,Bengkulu,ID,88.34,-3.8004,102.2655,Grage Hotel Bengkulu
9,26,Kirakira,SB,84.18,-10.4544,161.9205,SanBiz Lodge
10,27,Hithadhoo,MV,81.79,-0.6000,73.0833,Scoop Guest House
11,30,Mocuba,MZ,75.34,-16.8392,36.9856,Phama Lodge
12,33,Kieta,PG,85.10,-6.2167,155.6333,NaN
13,34,Esperance,AU,73.40,-33.8667,121.9000,Hospitality Esperance
14,36,Puerto Ayora,EC,75.99,-0.7393,-90.3518,Castillo Galapagos
15,37,Bambanglipuro,ID,84.78,-7.9500,110.2833,Puri Brata
16,39,Kavaratti,IN,81.41,10.5669,72.6420,Hotels in Lakshadweep Islands
17,42,Carnarvon,AU,82.40,-24.8667,113.6333,Hospitality Carnarvon
18,46,Meulaboh,ID,85.64,4.1363,96.1285,Kost Pria
19,48,Dingle,PH,85.32,10.9995,122.6711,SEGAYA PROPERTY

In [3]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.

info_box_template = """
<dl>
<dt>Name</dt><dd>{column1}</dd>
<dt>Another name</dt><dd>{column2}</dd>
</dl>
"""
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""
# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [4]:
# 4a. Add a marker layer for each city to the map.
locations = vacation_df[["Lat", "Lng"]]
max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [5]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[vacation_df['City'] == 'Lima']
vacation_end = vacation_df.loc[vacation_df['City'] == 'Lima']
vacation_stop1 = vacation_df.loc[vacation_df['City'] == 'Hualmay']
vacation_stop2 = vacation_df.loc[vacation_df['City'] == 'Huarmey'] 
vacation_stop3 = vacation_df.loc[vacation_df['City'] == 'Pisco']

vacation_start

    City_ID  City Country  Max Temp      Lat      Lng               Hotel Name
29       81  Lima      PE      77.0 -12.0432 -77.0282  Gran Hotel Bolivar Lima

In [6]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
#start = vacation_start.iloc[0,4:6].to_numpy()
#end = vacation_end.iloc[0,4:6].to_numpy()
#stop1 = vacation_stop1.iloc[0:4:6].to_numpy()
#stop2 = vacation_stop2.iloc[0,4:6].to_numpy()
#stop3 = vacation_stop3.iloc[0,4:6].to_numpy()

In [7]:
start = vacation_start["Lat"].to_numpy()[0], vacation_start["Lng"].to_numpy()[0]
end = vacation_end["Lat"].to_numpy()[0], vacation_end["Lng"].to_numpy()[0]
stop1 = vacation_stop1["Lat"].to_numpy()[0], vacation_stop1["Lng"].to_numpy()[0]
stop2 = vacation_stop2["Lat"].to_numpy()[0], vacation_stop2["Lng"].to_numpy()[0]
stop3 = vacation_stop3["Lat"].to_numpy()[0], vacation_stop3["Lng"].to_numpy()[0]
stop1

(-11.0964, -77.6139)

In [13]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
fig = gmaps.figure(center=(38, -122), zoom_level = 7)
lima = start
hualmay = stop1
huarmey = stop2
pisco = stop3
bike_ride = gmaps.directions_layer(lima, lima, 
                                   waypoints = [hualmay, huarmey, pisco], 
                                   travel_mode = "DRIVING")

In [14]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1,
                          vacation_stop2, vacation_stop3]
                         ,ignore_index=True)
itinerary_df

,City_ID,City,Country,Max Temp,Lat,Lng,Hotel Name
0,81,Lima,PE,77.00,-12.0432,-77.0282,Gran Hotel Bolivar Lima
1,443,Hualmay,PE,70.72,-11.0964,-77.6139,Hotel Villa Kitzia Huacho
2,711,Huarmey,PE,71.83,-10.0681,-78.1522,Hotel Miramar
3,96,Pisco,PE,71.60,-13.7000,-76.2167,Hotel San Isidro Oficial

In [15]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 

info_box_template = """
<dl>
<dt>Name</dt><dd>{column1}</dd>
<dt>Another name</dt><dd>{column2}</dd>
</dl>
"""
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [16]:
# 11a. Add a marker layer for each city to the map.
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)

# fig.add_layer(marker_layer)
fig.add_layer(bike_ride)

fig

Figure(layout=FigureLayout(height='420px'))

In [18]:

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
# 4a. Add a marker layer for each city to the map.

hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]
locations = itinerary_df[["Lat", "Lng"]]
locations = itinerary_df[["Lat", "Lng"]]
max_temp = itinerary_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))